DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  substance TEXT NOT NULL,
  dosage TEXT NOT NULL,
  duration TEXT NOT NULL,
  locations TEXT NOT NULL,
  activities TEXT NOT NULL,
  realizations TEXT NOT NULL,
  notes TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
